export default {
  fontFamilies: {
    sans: '"avenir next", avenir, sans-serif',
    serif: '"Garamond", serif',
  },
  colors: {
    white: '#fbfbfb',
    nearWhite: '#f1f1f1',
    lightGray: '#999',
    gray: '#777',
    midGray: '#555',
    darkGray: '#333',
  },
  breakpoints: ['50em', '60em'],
  fontSizes: [
    '.75rem',
    '.875rem',
    '1rem',
    '1.25rem',
    '1.5rem',
    '2.25rem',
    '3rem',
  ],
  maxWidth: '70rem',
  sizes: [
    '1rem',
    '2rem',
    '4rem',
    '8rem',
    '16rem',
    '32rem',
    '48rem',
    '64rem',
    '96rem',
  ],
  spacing: ['0', '.25rem', '.5rem', '1rem', '2rem', '4rem', '8rem', '16rem'],
};
