export default {
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#00f',
    secondary: '#00a',
    gray: '#eee',
    lightGrey: '#fafafa',
    midGrey: '#666',
    darkGrey: '#555',
    white: '#f4f4f4',
  },
  breakpoints: ['50em', '60em'],
  fontSizes: [
    '.75rem',
    '.875rem',
    '1rem',
    '1.25rem',
    '1.5rem',
    '2.25rem',
    '3rem',
  ],
  maxWidth: '70rem',
  sizes: [
    '1rem',
    '2rem',
    '4rem',
    '8rem',
    '16rem',
    '32rem',
    '48rem',
    '64rem',
    '96rem',
  ],
  spacing: ['0', '.25rem', '.5rem', '1rem', '2rem', '4rem', '8rem', '16rem'],
};
