export default {
  fonts: {
    sans: '"SourceSansProRegular",system,sans-serif',
    serif: 'Georgia,Times,Times New Roman,serif',
  },
  colors: {
    light: {
      accent: '#fb9a5a',
      background: '#f1f1f1',
      brightBackground: '#fbfbfb',
      foreground: '#2e2e2e',
      dimmedForeground: '#868686',
      extraDimmedForeground: '#ddd',
    },
    dark: {
      accent: '#ca7b46',
      background: '#242424',
      brightBackground: '#2e2e2e',
      foreground: '#ebebeb',
      dimmedForeground: '#a6a6a6',
      extraDimmedForeground: '#444',
    },
  },
  breakpoints: ['50em', '60em'],
  fontSizes: ['0.909rem', '1rem', '1.1rem', '1.21rem', '1.331rem'],
  maxWidth: '70rem',
  sizes: [
    '1rem',
    '2rem',
    '4rem',
    '8rem',
    '16rem',
    '32rem',
    '48rem',
    '64rem',
    '70rem',
    '96rem',
  ],
  space: [
    '0',
    '0.25rem',
    '0.5rem',
    '0.75rem',
    '1rem',
    '2rem',
    '3rem',
    '4rem',
    '8rem',
    '16rem',
  ],
};
